#Mock Email Campaign Data Analysis
##Context
The data are obtained from a hypothetical email campaign by serving 3 different Subject Lines across a three month period. There exist three tables for you to play around.

For this campaign, we consider as valid responses only the emails which were opened at the Sent Date (i.e. Sent_Date should be equal to Responded_Date.

##Modelling
Build a model which can predict the Open Rate based on the Customer’s attributes and the SubjetLine_ID received!

#Goals

###Unify sent_emails and responded
In order to find out which customers are set to "valid responses", a new binary column i'm gonna create. Value "1" if there's a valide response, "0" otherwise.

In [2]:
import numpy as np
import pandas as pd
import IPython.display as display
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [3]:
df_user = pd.read_csv("userbase.csv")
df_res = pd.read_csv("responded.csv")
df_sent = pd.read_csv("sent_emails.csv")

In [4]:
df_user

Customer_ID Gender Type                Email_Address  Age  Tenure
0                 1      M    C                  Mph@msn.com   38      12
1                 2      F    B  SophcYN7381qMe8lRqK@aol.com   37      23
2                 3      F    C                   xE@msn.com   32      15
3                 4      M    C          WduR0o0@comcast.net   31      24
4                 5      M    C     walHI9cmWJIBKvy0@aol.com   35      13
...             ...    ...  ...                          ...  ...     ...
294823       294824      F    B    HDDqmp046hcNu@hotmail.com   41      13
294824       294825      M    C                   7R@aol.com   36      23
294825       294826      M    C         XWprSNjVg2@yahoo.com   26      10
294826       294827      F    B         qJapyGhx@hotmail.com   38      12
294827       294828      F    B   9ob32uiYfdifdv@hotmail.com   25       1

[294828 rows x 6 columns]

In [5]:
df_res

Responded_Date  Customer_ID  SubjectLine_ID
0          2016-01-25       217102               3
1          2016-03-26       366875               2
2          2016-03-17       201561               2
3          2016-01-11       395345               3
4          2016-01-11       427539               3
...               ...          ...             ...
378203     2016-01-09        43156               1
378204     2016-03-16       397330               2
378205     2016-02-25       377520               1
378206     2016-02-04       146008               2
378207     2016-02-09       374971               3

[378208 rows x 3 columns]

In [6]:
df_sent

Sent_Date  Customer_ID  SubjectLine_ID
0       2016-01-28       1413.0             2.0
1       2016-03-02      83889.0             2.0
2       2016-03-09     457832.0             3.0
3       2016-01-20     127772.0             1.0
4       2016-02-03     192123.0             3.0
...            ...          ...             ...
555140  2016-01-12     290290.0             3.0
555141  2016-03-07     108545.0             3.0
555142  2016-03-08     390404.0             1.0
555143  2016-03-26      76094.0             2.0
555144  2016-03-18          NaN             NaN

[555145 rows x 3 columns]

In [7]:
df_tot = pd.merge(df_res, df_sent, on="Customer_ID")

In [12]:
df_tot

Responded_Date  Customer_ID  SubjectLine_ID_x   Sent_Date  \
0           2016-01-25       217102                 3  2016-02-20   
1           2016-01-25       217102                 3  2016-03-04   
2           2016-01-25       217102                 3  2016-01-23   
3           2016-01-25       217102                 3  2016-02-09   
4           2016-01-25       217102                 3  2016-03-21   
...                ...          ...               ...         ...   
2245317     2016-02-04       146008                 2  2016-01-11   
2245318     2016-02-04       146008                 2  2016-03-17   
2245319     2016-02-04       146008                 2  2016-01-12   
2245320     2016-02-04       146008                 2  2016-03-22   
2245321     2016-02-04       146008                 2  2016-02-11   

         SubjectLine_ID_y  
0                       3  
1                       3  
2                       3  
3                       1  
4                       1  
...                   ...  
2245317                 2  
2245318                 3  
2245319                 1  
2245320                 3  
2245321                 2  

[2245322 rows x 5 columns]

In [8]:
df_temp = df_tot
df_temp['Opened'] = (df_temp['Responded_Date'] == df_temp['Sent_Date']).astype(int)

In [26]:
df_temp

Responded_Date  Customer_ID  SubjectLine_ID_x   Sent_Date  \
0           2016-01-25       217102                 3  2016-02-20   
1           2016-01-25       217102                 3  2016-03-04   
2           2016-01-25       217102                 3  2016-01-23   
3           2016-01-25       217102                 3  2016-02-09   
4           2016-01-25       217102                 3  2016-03-21   
...                ...          ...               ...         ...   
2245317     2016-02-04       146008                 2  2016-01-11   
2245318     2016-02-04       146008                 2  2016-03-17   
2245319     2016-02-04       146008                 2  2016-01-12   
2245320     2016-02-04       146008                 2  2016-03-22   
2245321     2016-02-04       146008                 2  2016-02-11   

         SubjectLine_ID_y  Opened  
0                       3       0  
1                       3       0  
2                       3       0  
3                       1       0  
4                       1       0  
...                   ...     ...  
2245317                 2       0  
2245318                 3       0  
2245319                 1       0  
2245320                 3       0  
2245321                 2       0  

[2245322 rows x 6 columns]

In [9]:
df_new = df_tot.drop(df_tot[df_tot.Responded_Date != df_tot.Sent_Date].index)

In [18]:
df_new

Responded_Date  Customer_ID  SubjectLine_ID_x   Sent_Date  \
8           2016-03-26       366875                 2  2016-03-26   
16          2016-01-08       201561                 3  2016-01-08   
17          2016-01-11       395345                 3  2016-01-11   
27          2016-01-11       427539                 3  2016-01-11   
30          2016-02-05       141763                 1  2016-02-05   
...                ...          ...               ...         ...   
2245278     2016-01-19       192537                 2  2016-01-19   
2245288     2016-03-26       225065                 2  2016-03-26   
2245301     2016-01-05         4855                 3  2016-01-05   
2245310     2016-03-16       397330                 2  2016-03-16   
2245314     2016-02-04       146008                 2  2016-02-04   

         SubjectLine_ID_y  
8                       2  
16                      3  
17                      3  
27                      3  
30                      1  
...                   ...  
2245278                 1  
2245288                 2  
2245301                 3  
2245310                 2  
2245314                 2  

[243175 rows x 5 columns]

In [10]:
df = pd.merge(df_temp, df_user, on='Customer_ID')

In [11]:
df.drop('Email_Address', axis=1, inplace=True)
df.drop('Responded_Date', axis=1, inplace=True)
df.drop('Sent_Date', axis=1, inplace=True)

In [29]:
df

Customer_ID  SubjectLine_ID_x  SubjectLine_ID_y  Opened Gender Type  \
0             217102                 3                 3       0      F    C   
1             217102                 3                 3       0      F    C   
2             217102                 3                 3       0      F    C   
3             217102                 3                 1       0      F    C   
4             217102                 3                 1       0      F    C   
...              ...               ...               ...     ...    ...  ...   
2245317       146008                 2                 2       0      M    B   
2245318       146008                 2                 3       0      M    B   
2245319       146008                 2                 1       0      M    B   
2245320       146008                 2                 3       0      M    B   
2245321       146008                 2                 2       0      M    B   

         Age  Tenure  
0         21      16  
1         21      16  
2         21      16  
3         21      16  
4         21      16  
...      ...     ...  
2245317   48      19  
2245318   48      19  
2245319   48      19  
2245320   48      19  
2245321   48      19  

[2245322 rows x 8 columns]

##Feature Engineering

In [49]:
# Assuming df is your DataFrame with the dataset
df['Gender'] = df['Gender'].map({'M': 0, 'F': 1})
df['Type'] = df['Type'].map({'B': 0, 'C': 1})


In [50]:
df

Customer_ID  SubjectLine_ID_x  SubjectLine_ID_y  Opened  Gender  Type  \
0            217102                 3               3.0       0       1     1   
1            217102                 3               3.0       0       1     1   
2            201561                 2               1.0       0       0     1   
3            201561                 3               1.0       0       0     1   
4            141763                 1               3.0       0       0     1   
...             ...               ...               ...     ...     ...   ...   
296572       225065                 2               2.0       1       0     0   
296573       225065                 2               2.0       0       0     0   
296574       146008                 2               2.0       1       0     0   
296575       146008                 2               2.0       0       0     0   
296576       146008                 2               2.0       0       0     0   

        Age  Tenure  
0        21      16  
1        21      16  
2        18      13  
3        18      13  
4        20      22  
...     ...     ...  
296572   46      14  
296573   46      14  
296574   48      19  
296575   48      19  
296576   48      19  

[296577 rows x 8 columns]

In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Assuming df is your DataFrame with the dataset
# df = ...

# Define features (X) and target variable (y)
X = df[['SubjectLine_ID_x', 'SubjectLine_ID_y', 'Gender', 'Type', 'Age', 'Tenure']]
y = df['Opened']

# Convert categorical variables to numerical using one-hot encoding
X = pd.get_dummies(X, columns=['Gender', 'Type'], drop_first=True)

# Standardize the features
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)

# Apply PCA for dimensionality reduction
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_standardized)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# Create a Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Display the evaluation metrics
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_rep)


Accuracy: 0.8872985366511565
Confusion Matrix:
 [[52514   400]
 [ 6285   117]]
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.99      0.94     52914
           1       0.23      0.02      0.03      6402

    accuracy                           0.89     59316
   macro avg       0.56      0.51      0.49     59316
weighted avg       0.82      0.89      0.84     59316



In [25]:
# Feature Importance Analysis
feature_importances = model.feature_importances_
print("Feature Importances:", feature_importances)

Feature Importances: [0.11468203 0.88531797]


In [26]:
# Assuming df is your original DataFrame with column names
feature_names = X.columns

# Display feature names with their corresponding importances
feature_importance_dict = dict(zip(feature_names, feature_importances))
print("Feature Importances:")
for feature, importance in sorted(feature_importance_dict.items(), key=lambda x: x[1], reverse=True):
    print(f"{feature}: {importance}")

Feature Importances:
SubjectLine_ID_y: 0.8853179679857645
SubjectLine_ID_x: 0.11468203201423562


In [30]:
from imblearn.over_sampling import SMOTE


In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming df is your DataFrame with the dataset
# df = ...

# Define features (X) and target variable (y)
X = df[['SubjectLine_ID_x', 'SubjectLine_ID_y', 'Gender', 'Type', 'Age', 'Tenure']]
y = df['Opened']

# Convert categorical variables to numerical using one-hot encoding
X = pd.get_dummies(X, columns=['Gender', 'Type'], drop_first=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply SMOTE to the training data
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

# Create a Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the resampled training data
model.fit(X_resampled, y_resampled)

# Predict on the test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Display the evaluation metrics
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_rep)


Accuracy: 0.6874704969991233
Confusion Matrix:
 [[35814 17100]
 [ 1438  4964]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.68      0.79     52914
           1       0.22      0.78      0.35      6402

    accuracy                           0.69     59316
   macro avg       0.59      0.73      0.57     59316
weighted avg       0.88      0.69      0.75     59316



In [52]:
import xgboost as xgb

In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import xgboost as xgb

# Assuming df is your DataFrame with the dataset
# df = ...

# Define features (X) and target variable (y)
X = df[['SubjectLine_ID_x', 'SubjectLine_ID_y', 'Gender', 'Type', 'Age', 'Tenure']]
y = df['Opened']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an XGBoost classifier
model = xgb.XGBClassifier(objective='binary:logistic', random_state=42)

# Train the model on the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Display the evaluation metrics
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_rep)


Accuracy: 0.8916649807809023
Confusion Matrix:
 [[52887    27]
 [ 6399     3]]
Classification Report:
               precision    recall  f1-score   support

           0       0.89      1.00      0.94     52914
           1       0.10      0.00      0.00      6402

    accuracy                           0.89     59316
   macro avg       0.50      0.50      0.47     59316
weighted avg       0.81      0.89      0.84     59316



In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import xgboost as xgb

# Assuming df is your DataFrame with the dataset
# df = ...

# Define features (X) and target variable (y)
X = df[['SubjectLine_ID_x', 'SubjectLine_ID_y', 'Gender', 'Type', 'Age', 'Tenure']]
y = df['Opened']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Adjust class weights for imbalance
class_weights = len(y_train) / (2 * np.bincount(y_train))
weights = {0: class_weights[0], 1: class_weights[1]}

# Create an XGBoost classifier with adjusted class weights
model = xgb.XGBClassifier(objective='binary:logistic', scale_pos_weight=weights[1], random_state=42)

# Train the model on the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Display the evaluation metrics
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_rep)


Accuracy: 0.6666666666666666
Confusion Matrix:
 [[33880 19034]
 [  738  5664]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.64      0.77     52914
           1       0.23      0.88      0.36      6402

    accuracy                           0.67     59316
   macro avg       0.60      0.76      0.57     59316
weighted avg       0.90      0.67      0.73     59316



In [56]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# Create base classifiers
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
xgb_classifier = xgb.XGBClassifier(objective='binary:logistic', scale_pos_weight=weights[1], random_state=42)

# Create a stacking classifier with Logistic Regression as the final estimator
stacking_classifier = StackingClassifier(
    estimators=[('rf', rf_classifier), ('xgb', xgb_classifier)],
    final_estimator=LogisticRegression(),
    stack_method='auto',
)

# Train the stacking classifier on the training data
stacking_classifier.fit(X_train, y_train)

# Predict on the test data
y_pred_stacking = stacking_classifier.predict(X_test)

# Evaluate the stacking classifier
accuracy_stacking = accuracy_score(y_test, y_pred_stacking)
conf_matrix_stacking = confusion_matrix(y_test, y_pred_stacking)
classification_rep_stacking = classification_report(y_test, y_pred_stacking)

# Display the evaluation metrics for the stacking classifier
print("Stacking Classifier Accuracy:", accuracy_stacking)
print("Stacking Classifier Confusion Matrix:\n", conf_matrix_stacking)
print("Stacking Classifier Classification Report:\n", classification_rep_stacking)


Stacking Classifier Accuracy: 0.8919347225032032
Stacking Classifier Confusion Matrix:
 [[52901    13]
 [ 6397     5]]
Stacking Classifier Classification Report:
               precision    recall  f1-score   support

           0       0.89      1.00      0.94     52914
           1       0.28      0.00      0.00      6402

    accuracy                           0.89     59316
   macro avg       0.58      0.50      0.47     59316
weighted avg       0.83      0.89      0.84     59316



In [58]:
import numpy as np
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb

# Assuming df is your DataFrame with the dataset
# df = ...

# Define features (X) and target variable (y)
X = df[['SubjectLine_ID_x', 'SubjectLine_ID_y', 'Gender', 'Type', 'Age', 'Tenure']]
y = df['Opened']

# Create base classifiers
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
xgb_classifier = xgb.XGBClassifier(objective='binary:logistic', random_state=42)

# Create a stacking classifier with Logistic Regression as the final estimator
stacking_classifier = StackingClassifier(
    estimators=[('rf', rf_classifier), ('xgb', xgb_classifier)],
    final_estimator=LogisticRegression(),
    stack_method='auto',
    cv=StratifiedKFold(n_splits=5),  # Number of folds for cross-validation
)

# Perform cross-validation
cv_scores = cross_val_score(stacking_classifier, X, y, cv=StratifiedKFold(n_splits=5), scoring='accuracy')

# Display cross-validation results
print("Cross-Validation Scores:", cv_scores)
print("Mean Accuracy:", np.mean(cv_scores))


Cross-Validation Scores: [0.89233934 0.89210331 0.89178117 0.89221951 0.88704375]
Mean Accuracy: 0.8910974140010245
